<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="5" passed="0" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-04-24T11:34:51 IST" name="RegressionTesting" finished-at="2021-04-24T11:34:52 IST" duration-ms="348">
    <groups>
      <group name="RegressionTest">
        <method signature="AdditionTestCases.TestAdditionWithOnePositiveOneNegative()[pri:2, instance:QualityKiosksTraining.CalculatorAPI.AdditionTestCases@175b9425]" name="TestAdditionWithOnePositiveOneNegative" class="QualityKiosksTraining.CalculatorAPI.AdditionTestCases"/>
        <method signature="AdditionTestCases.TestAdditionWithPositiveNumbers()[pri:1, instance:QualityKiosksTraining.CalculatorAPI.AdditionTestCases@175b9425]" name="TestAdditionWithPositiveNumbers" class="QualityKiosksTraining.CalculatorAPI.AdditionTestCases"/>
        <method signature="TestDivisionFunctionality.TestDivisionWithPositiveValues()[pri:1, instance:QualityKiosksTraining.CalculatorAPI.TestDivisionFunctionality@3c947bc5]" name="TestDivisionWithPositiveValues" class="QualityKiosksTraining.CalculatorAPI.TestDivisionFunctionality"/>
      </group> <!-- RegressionTest -->
    </groups>
    <test started-at="2021-04-24T11:34:51 IST" name="AdditionTestCases" finished-at="2021-04-24T11:34:52 IST" duration-ms="151">
      <class name="QualityKiosksTraining.CalculatorAPI.AdditionTestCases">
        <test-method signature="TestAdditionWithPositiveNumbers()[pri:1, instance:QualityKiosksTraining.CalculatorAPI.AdditionTestCases@175b9425]" started-at="2021-04-24T11:34:51 IST" name="TestAdditionWithPositiveNumbers" finished-at="2021-04-24T11:34:52 IST" duration-ms="48" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "QualityKiosksTraining.CalculatorAPI.Calculator.Addition(int, int)" because "this.Obj" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "QualityKiosksTraining.CalculatorAPI.Calculator.Addition(int, int)" because "this.Obj" is null
at QualityKiosksTraining.CalculatorAPI.AdditionTestCases.TestAdditionWithPositiveNumbers(AdditionTestCases.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestAdditionWithPositiveNumbers -->
        <test-method signature="TestAdditionWithOnePositiveOneNegative()[pri:2, instance:QualityKiosksTraining.CalculatorAPI.AdditionTestCases@175b9425]" started-at="2021-04-24T11:34:52 IST" name="TestAdditionWithOnePositiveOneNegative" finished-at="2021-04-24T11:34:52 IST" duration-ms="6" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "QualityKiosksTraining.CalculatorAPI.Calculator.Addition(int, int)" because "this.Obj" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "QualityKiosksTraining.CalculatorAPI.Calculator.Addition(int, int)" because "this.Obj" is null
at QualityKiosksTraining.CalculatorAPI.AdditionTestCases.TestAdditionWithOnePositiveOneNegative(AdditionTestCases.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestAdditionWithOnePositiveOneNegative -->
      </class> <!-- QualityKiosksTraining.CalculatorAPI.AdditionTestCases -->
    </test> <!-- AdditionTestCases -->
    <test started-at="2021-04-24T11:34:52 IST" name="Testing Division Functionality" finished-at="2021-04-24T11:34:52 IST" duration-ms="11">
      <class name="QualityKiosksTraining.CalculatorAPI.TestDivisionFunctionality">
        <test-method signature="TestDivisionWithPositiveValues()[pri:1, instance:QualityKiosksTraining.CalculatorAPI.TestDivisionFunctionality@3c947bc5]" started-at="2021-04-24T11:34:52 IST" name="TestDivisionWithPositiveValues" finished-at="2021-04-24T11:34:52 IST" duration-ms="5" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "QualityKiosksTraining.CalculatorAPI.Calculator.Division(int, int)" because "this.Cal" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "QualityKiosksTraining.CalculatorAPI.Calculator.Division(int, int)" because "this.Cal" is null
at QualityKiosksTraining.CalculatorAPI.TestDivisionFunctionality.TestDivisionWithPositiveValues(TestDivisionFunctionality.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestDivisionWithPositiveValues -->
      </class> <!-- QualityKiosksTraining.CalculatorAPI.TestDivisionFunctionality -->
    </test> <!-- Testing Division Functionality -->
  </suite> <!-- RegressionTesting -->
</testng-results>
